#!/usr/bin/env python3
"""
Linker MemMap Viewer — with ELF symbol analysis
=================================================
Run:   python linker_viewer.py
Opens: http://localhost:5000  (auto-scans for free port)

Optional ELF analysis:
  Provide paths to arm-none-eabi-nm, arm-none-eabi-readelf,
  arm-none-eabi-objdump, arm-none-eabi-size, arm-none-eabi-addr2line
  via the Settings panel in the browser.

Requires:  pip install bottle
"""

import re, sys, json, os, subprocess, shutil, webbrowser, threading, socket
from pathlib import Path

try:
    from bottle import Bottle, request, response, run
except ImportError:
    print("\n[ERROR] bottle not installed.  Fix:  pip install bottle\n")
    sys.exit(1)

app = Bottle()

# ─────────────────────────────────────────────────────────────────────────────
# LINKER SCRIPT PARSER
# ─────────────────────────────────────────────────────────────────────────────

SECTION_HINTS = {
    ".text":                    ("Code",       "Compiled C/C++ functions — your application logic"),
    ".startup":                 ("Code",       "Reset handler and startup assembly (runs before main)"),
    ".systeminit":              ("Code",       "Clock, watchdog, and core init called before main()"),
    ".intc_vector":             ("Vectors",    "Interrupt vector table — ISR function pointers for every IRQ"),
    ".isr_vector":              ("Vectors",    "STM32-style interrupt vector table"),
    ".core_loop":               ("Code",       "Core idle/wait loop"),
    ".init":                    ("Code",       "C runtime .init functions (called before main)"),
    ".fini":                    ("Code",       "C runtime .fini functions (called at exit)"),
    ".itcm_text":               ("ITCM Code",  "Performance-critical code in Instruction TCM — zero wait-state, fastest execution"),
    ".acfls_code_rom":          ("Flash Acc",  "Flash driver code stored in ROM — copied to RAM before use"),
    ".acfls_code_ram":          ("Flash Acc",  "Flash driver running from RAM — REQUIRED during erase/write"),
    ".acmem_43_infls_code_rom": ("Flash Acc",  "Internal flash memory driver code in ROM"),
    ".acmem_43_infls_code_ram": ("Flash Acc",  "Internal flash memory driver running from RAM"),
    ".rodata":                  ("RO Data",    "Read-only data — string literals, const globals, lookup tables"),
    ".mcal_const":              ("RO Data",    "MCAL driver constant data — peripheral configurations"),
    ".mcal_const_cfg":          ("RO Data",    "MCAL configuration structures generated by tooling"),
    ".mcal_const_no_cacheable": ("RO Data NC", "MCAL constants in non-cacheable SRAM for DMA access"),
    ".boot_header":             ("Boot",       "Boot configuration header consumed by ROM bootloader or HSE"),
    ".pflash":                  ("Flash",      "Primary flash section — code and read-only data"),
    ".data":                    ("Init Data",  "Initialised globals/statics — stored in flash, COPIED to SRAM at startup"),
    ".mcal_data":               ("Init Data",  "MCAL driver state — initialised globals for peripheral drivers"),
    ".ramcode":                 ("Init Data",  "Code that must run from RAM (e.g. during flash ops)"),
    ".dtcm_data":               ("DTCM Data",  "Initialised data in Data TCM — zero wait-state, for hot variables"),
    ".mcal_data_no_cacheable":  ("NC Data",    "Driver data in non-cacheable SRAM — for DMA-controlled peripherals"),
    ".non_cacheable_data":      ("NC Data",    "Non-cacheable SRAM — DMA buffers, IPC frames go here"),
    ".mcal_shared_data":        ("Shared",     "Initialised data shared between cores"),
    ".shareable_data":          ("Shared",     "Shareable memory region — accessible by multiple cores"),
    ".bss":                     ("BSS",        "Uninitialised globals/statics — zeroed at startup, costs NO flash"),
    ".mcal_bss":                ("BSS",        "Uninitialised MCAL driver state — zeroed at startup"),
    ".dtcm_bss":                ("DTCM BSS",   "Uninitialised data in Data TCM — zeroed at startup"),
    ".mcal_bss_no_cacheable":   ("NC BSS",     "Uninitialised non-cacheable SRAM — DMA buffers"),
    ".non_cacheable_bss":       ("NC BSS",     "Uninitialised non-cacheable SRAM region"),
    ".mcal_shared_bss":         ("Shared BSS", "Uninitialised shared memory between cores"),
    ".shareable_bss":           ("Shared BSS", "Uninitialised shareable memory"),
    ".standby_data":            ("Standby",    "Data preserved across low-power standby — NOT zeroed on wakeup"),
    ".heap":                    ("Heap",       "Dynamic memory arena — malloc/free. Keep small in safety-critical code"),
    "_user_heap_stack":         ("Heap+Stack", "STM32 CubeMX combined heap and stack reservation"),
    ".stack":                   ("Stack",      "Main stack — local variables, function frames, IRQ stack. Overflow = HardFault"),
    ".int_vector":              ("Vect RAM",   "Vector table copied to RAM — enables runtime IRQ handler remapping via VTOR"),
    ".int_results":             ("Results",    "Test/BIST measurement results storage"),
    ".ARM":                     ("ARM Init",   "ARM runtime init/fini arrays"),
    ".preinit_array":           ("Init Array", "Pre-init constructor pointers"),
    ".init_array":              ("Init Array", "Global constructor pointers — C++ static object init, called before main()"),
    ".fini_array":              ("Fini Array", "Global destructor pointers — C++ static object destruction"),
    ".sram_data":               ("Init Data",  "Initialised data section placed in SRAM"),
    ".sram_bss":                ("BSS",        "Uninitialised SRAM data"),
    ".data_tcm_data":           ("DTCM Data",  "Initialised data mapped to Data TCM"),
    ".bss_tcm_data":            ("DTCM BSS",   "Uninitialised data in Data TCM"),
}

TYPE_COLORS = {
    "Code":       "#3b82f6", "ITCM Code":  "#06b6d4", "Flash Acc":  "#8b5cf6",
    "Vectors":    "#f59e0b", "Vect RAM":   "#f59e0b", "RO Data":    "#10b981",
    "RO Data NC": "#059669", "Boot":       "#6366f1", "Flash":      "#2563eb",
    "Init Data":  "#f97316", "DTCM Data":  "#fb923c", "NC Data":    "#ef4444",
    "Shared":     "#ec4899", "Shared BSS": "#a855f7", "BSS":        "#64748b",
    "DTCM BSS":   "#475569", "NC BSS":     "#94a3b8", "Standby":    "#14b8a6",
    "Heap":       "#84cc16", "Heap+Stack": "#65a30d", "Stack":      "#a3e635",
    "Results":    "#6b7280", "ARM Init":   "#8b5cf6", "Init Array": "#7c3aed",
    "Fini Array": "#6d28d9", "Unknown":    "#374151",
}

REGION_COLORS = {
    "flash": "#0d2140", "sram": "#0d2818", "itcm": "#0d1e33",
    "dtcm":  "#1a0d33", "dflash": "#1e1e0d", "default": "#141420",
}

# DMA-safety: sections that MUST be non-cacheable for DMA safety
DMA_SAFE_SECTIONS = {".non_cacheable_data", ".non_cacheable_bss",
                     ".mcal_data_no_cacheable", ".mcal_bss_no_cacheable"}
CACHEABLE_SECTIONS = {".data", ".bss", ".sram_data", ".sram_bss",
                      ".dtcm_data", ".dtcm_bss"}

def parse_value(s):
    s = s.strip()
    try:
        s2 = re.sub(r'(?i)0x([0-9a-f]+)', lambda m: str(int(m.group(1), 16)), s)
        s2 = re.sub(r'(?i)(\d+)[kK]', lambda m: str(int(m.group(1))*1024), s2)
        s2 = re.sub(r'(?i)(\d+)[mM]', lambda m: str(int(m.group(1))*1048576), s2)
        return int(eval(s2))
    except:
        return 0

def strip_comments(text):
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    text = re.sub(r'//[^\n]*', '', text)
    return text

def classify_region(name, attrs):
    n, a = name.lower(), attrs.lower()
    if 'itcm' in n:                               return 'itcm'
    if 'dtcm' in n or 'stack' in n:               return 'dtcm'
    if 'dflash' in n or 'data_flash' in n:        return 'dflash'
    if 'flash' in n or 'rom' in n or ('r' in a and 'x' in a): return 'flash'
    if 'sram' in n or 'ram' in n:                 return 'sram'
    return 'default'

def parse_linker_script(content):
    content = strip_comments(content)
    regions, reg_map = [], {}

    mb = re.search(r'MEMORY\s*\{([^}]+)\}', content, re.DOTALL)
    if mb:
        for m in re.finditer(
            r'(\w+)\s*(?:\(([^)]*)\))?\s*:\s*ORIGIN\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*,'
            r'\s*LENGTH\s*=\s*(0x[0-9A-Fa-f]+|\d+)',
            mb.group(1)
        ):
            name, attrs = m.group(1), (m.group(2) or '').strip()
            origin, length = parse_value(m.group(3)), parse_value(m.group(4))
            rtype = classify_region(name, attrs)
            reg = {"name": name, "attrs": attrs, "origin": origin,
                   "length": length, "end": origin+length, "type": rtype,
                   "color": REGION_COLORS.get(rtype, REGION_COLORS["default"]),
                   "sections": [], "used_bytes": 0}
            regions.append(reg)
            reg_map[name] = reg

    sections = []
    sb = re.search(r'SECTIONS\s*\{(.+)', content, re.DOTALL)
    if sb:
        for m in re.finditer(
            r'(\.[\w.]+)\s*(?:\([^)]*\))?\s*(?::\s*(?:AT\s*\([^)]+\)\s*)?)?'
            r'\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}[^>]*>\s*(\w+)?(?:\s*AT\s*>\s*(\w+))?',
            sb.group(1), re.DOTALL
        ):
            sname = m.group(1)
            noload = bool(re.search(r'\bNOLOAD\b', m.group(0)))
            vma, lma = m.group(3), m.group(4)
            hint = next((k for k in SECTION_HINTS if sname.startswith(k)), None)
            stype, sdesc = SECTION_HINTS.get(hint or sname, ("Unknown","Section purpose not catalogued"))
            dma_safe = sname in DMA_SAFE_SECTIONS
            cacheable = sname in CACHEABLE_SECTIONS
            sec = {"name": sname, "vma": vma, "lma": lma, "noload": noload,
                   "type": stype, "desc": sdesc, "dma_safe": dma_safe,
                   "cacheable": cacheable,
                   "color": TYPE_COLORS.get(stype, TYPE_COLORS["Unknown"]),
                   "size": 0, "symbols": []}
            sections.append(sec)
            if vma and vma in reg_map:
                reg_map[vma]["sections"].append(sec)

    entry = ""
    em = re.search(r'ENTRY\s*\((\w+)\)', content)
    if em: entry = em.group(1)

    return {"regions": regions, "sections": sections,
            "entry": entry, "reg_map": {k: i for i,k in enumerate(reg_map)}}


# ─────────────────────────────────────────────────────────────────────────────
# ELF ANALYSIS ENGINE
# ─────────────────────────────────────────────────────────────────────────────

NM_TYPE_MAP = {
    'T': 'function',   't': 'function',    # text/code
    'D': 'variable',   'd': 'variable',    # init data
    'B': 'variable',   'b': 'variable',    # BSS
    'R': 'constant',   'r': 'constant',    # read-only
    'W': 'weak',       'w': 'weak',        # weak symbols
    'U': 'undefined',                       # undefined (external)
    'A': 'absolute',                        # absolute
    'C': 'common',                          # common (uninit)
    'I': 'indirect',
    'V': 'weak_obj',   'v': 'weak_obj',
    'G': 'small_data', 'g': 'small_data',
    'S': 'small_bss',  's': 'small_bss',
}

SYMBOL_COLORS = {
    'function':   '#3b82f6',
    'variable':   '#f97316',
    'constant':   '#10b981',
    'weak':       '#6366f1',
    'undefined':  '#6e7681',
    'absolute':   '#f59e0b',
    'common':     '#8b5cf6',
    'weak_obj':   '#6366f1',
    'small_data': '#f97316',
    'small_bss':  '#64748b',
    'indirect':   '#ec4899',
    'other':      '#374151',
}

def run_tool(args, timeout=15):
    """Run an external tool, return (stdout, stderr, returncode)."""
    try:
        r = subprocess.run(args, capture_output=True, text=True,
                          timeout=timeout, errors='replace')
        return r.stdout, r.stderr, r.returncode
    except FileNotFoundError:
        return '', f"Tool not found: {args[0]}", 1
    except subprocess.TimeoutExpired:
        return '', f"Timeout running: {' '.join(args)}", 1
    except Exception as e:
        return '', str(e), 1

def parse_nm(nm_path, elf_path):
    """
    Run nm --print-size --size-sort --radix=x on the ELF.
    Returns list of symbol dicts.
    """
    stdout, stderr, rc = run_tool([
        nm_path, '--print-size', '--radix=x', '--format=posix',
        '--special-syms', elf_path
    ])
    if rc != 0 or not stdout.strip():
        # Fallback without --special-syms
        stdout, stderr, rc = run_tool([
            nm_path, '--print-size', '--radix=x', '--format=posix', elf_path
        ])

    symbols = []
    for line in stdout.splitlines():
        line = line.strip()
        if not line: continue
        # posix format: name type value [size]
        parts = line.split()
        if len(parts) < 3: continue
        name = parts[0]
        ntype_raw = parts[1]
        try:
            addr = int(parts[2], 16)
            size = int(parts[3], 16) if len(parts) > 3 else 0
        except ValueError:
            continue

        ntype = NM_TYPE_MAP.get(ntype_raw, 'other')
        is_global = ntype_raw.isupper()

        # Skip internal/boring symbols
        if name.startswith('$') or name in ('', '_', '__'):
            continue

        symbols.append({
            "name":     name,
            "addr":     addr,
            "size":     size,
            "type":     ntype,
            "type_raw": ntype_raw,
            "global":   is_global,
            "color":    SYMBOL_COLORS.get(ntype, SYMBOL_COLORS['other']),
        })

    return sorted(symbols, key=lambda s: s['addr'])


def parse_readelf_sections(readelf_path, elf_path):
    """
    Run readelf -S to get section headers with addresses and sizes.
    Returns dict: section_name -> {addr, offset, size, type, flags}
    """
    stdout, _, rc = run_tool([readelf_path, '-S', '--wide', elf_path])
    sections = {}
    for line in stdout.splitlines():
        # [ Nr] Name  Type  Addr  Off  Size  ES Flg Lk Inf Al
        m = re.match(
            r'\s*\[\s*\d+\]\s+(\S+)\s+(\S+)\s+([0-9a-fA-F]+)\s+'
            r'([0-9a-fA-F]+)\s+([0-9a-fA-F]+)', line)
        if m:
            name  = m.group(1)
            stype = m.group(2)
            addr  = int(m.group(3), 16)
            size  = int(m.group(5), 16)
            flags_m = re.search(r'\d+\s+(\S*)\s+\d+\s+\d+\s+\d+\s*$', line)
            flags = flags_m.group(1) if flags_m else ''
            sections[name] = {"addr": addr, "size": size,
                              "type": stype, "flags": flags}
    return sections


def parse_size(size_path, elf_path):
    """Run size -A for per-section sizes."""
    stdout, _, rc = run_tool([size_path, '-A', '-x', elf_path])
    sizes = {}
    for line in stdout.splitlines():
        m = re.match(r'^(\S+)\s+(0x[0-9a-fA-F]+|\d+)\s+(0x[0-9a-fA-F]+|\d+)', line)
        if m:
            try:
                sizes[m.group(1)] = {'size': int(m.group(2),0), 'addr': int(m.group(3),0)}
            except:
                pass
    return sizes


def addr2line_lookup(addr2line_path, elf_path, addresses):
    """Bulk addr2line lookup. Returns dict addr(int) -> 'file:line'"""
    if not addresses:
        return {}
    addr_strs = [hex(a) for a in addresses]
    stdout, _, rc = run_tool(
        [addr2line_path, '-e', elf_path, '-f', '-C', '-p'] + addr_strs,
        timeout=30
    )
    result = {}
    lines = stdout.splitlines()
    for i, addr in enumerate(addresses):
        if i < len(lines):
            result[addr] = lines[i].strip()
    return result


def assign_symbols_to_sections(symbols, elf_sections, ld_sections):
    """
    Map each symbol to a linker section by address range.
    Also detect symbols that fall outside all known sections (linker bugs).
    """
    # Build sorted list of (start, end, sec_name) from ELF sections
    ranges = []
    for name, s in elf_sections.items():
        if s['size'] > 0:
            ranges.append((s['addr'], s['addr'] + s['size'], name))
    ranges.sort()

    sec_map = {s['name']: s for s in ld_sections}
    orphans = []

    for sym in symbols:
        if sym['addr'] == 0 or sym['type'] == 'undefined':
            continue
        matched = None
        for start, end, sname in ranges:
            if start <= sym['addr'] < end:
                matched = sname
                break
        sym['section'] = matched
        if matched and matched in sec_map:
            sec_map[matched]['symbols'].append(sym)
            sec_map[matched]['size'] = sec_map[matched].get('size', 0) + sym['size']
        elif matched is None:
            orphans.append(sym)

    return orphans


def generate_warnings(ld_data, elf_sections, symbols):
    """Generate actionable warnings for the Warnings tab."""
    warnings = []

    # 1. Section overflow
    for reg in ld_data['regions']:
        used = sum(elf_sections.get(s['name'], {}).get('size', 0) for s in reg['sections'])
        if reg['length'] > 0:
            pct = used / reg['length']
            if pct > 0.95:
                warnings.append({
                    "level": "error",
                    "category": "Memory Overflow",
                    "message": f"{reg['name']} is {pct*100:.1f}% full ({used:,} / {reg['length']:,} bytes)",
                    "detail": "Region is nearly full. Risk of linker error on next build."
                })
            elif pct > 0.80:
                warnings.append({
                    "level": "warn",
                    "category": "Memory Pressure",
                    "message": f"{reg['name']} is {pct*100:.1f}% full ({used:,} / {reg['length']:,} bytes)",
                    "detail": "Consider moving large constants to flash or enabling LTO."
                })

    # 2. DMA safety — large variables in cacheable SRAM
    cacheable_addrs = set()
    for sec in ld_data['sections']:
        if sec['cacheable']:
            es = elf_sections.get(sec['name'], {})
            if es:
                cacheable_addrs.add((es.get('addr',0), es.get('addr',0)+es.get('size',0)))

    dma_keywords = ['buf', 'buffer', 'frame', 'ipc', 'spi', 'dma', 'rx', 'tx', 'fifo']
    for sym in symbols:
        if sym['size'] >= 4 and sym['type'] in ('variable',):
            name_l = sym['name'].lower()
            if any(k in name_l for k in dma_keywords):
                for start, end in cacheable_addrs:
                    if start <= sym['addr'] < end:
                        warnings.append({
                            "level": "warn",
                            "category": "DMA Safety",
                            "message": f"'{sym['name']}' ({sym['size']} B) is in cacheable SRAM",
                            "detail": f"Address 0x{sym['addr']:08X}. If used with DMA, cache coherency "
                                      f"issues will cause silent data corruption. Move to .non_cacheable_bss."
                        })
                        break

    # 3. Large symbols eating RAM
    ram_syms = [s for s in symbols if s['size'] > 1024 and s['type'] in ('variable','common')]
    ram_syms.sort(key=lambda s: -s['size'])
    for sym in ram_syms[:5]:
        warnings.append({
            "level": "info",
            "category": "Large Symbol",
            "message": f"'{sym['name']}' uses {sym['size']:,} bytes of RAM",
            "detail": f"Address 0x{sym['addr']:08X}, section: {sym.get('section','?')}. "
                      f"Consider if this can be flash (const) or reduced in size."
        })

    # 4. Large functions (potential stack pressure)
    big_fns = [s for s in symbols if s['size'] > 4096 and s['type'] == 'function']
    big_fns.sort(key=lambda s: -s['size'])
    for sym in big_fns[:5]:
        warnings.append({
            "level": "info",
            "category": "Large Function",
            "message": f"'{sym['name']}' is {sym['size']:,} bytes of code",
            "detail": f"Large functions increase I-cache pressure and may indicate "
                      f"missing -Os or opportunities to split into smaller units."
        })

    # 5. Undefined symbols (linker would have caught these, but nm shows them)
    undef = [s for s in symbols if s['type'] == 'undefined']
    if undef:
        warnings.append({
            "level": "info",
            "category": "Undefined Symbols",
            "message": f"{len(undef)} undefined symbol(s) referenced",
            "detail": "These are resolved by the linker from libraries. "
                      + ", ".join(s['name'] for s in undef[:8])
                      + ("..." if len(undef) > 8 else "")
        })

    return warnings


def compute_startup_cost(ld_sections, elf_sections):
    """Compute flash→RAM copy sizes for startup cost analysis."""
    items = []
    total_copy = 0
    total_zero = 0
    for sec in ld_sections:
        es = elf_sections.get(sec['name'], {})
        sz = es.get('size', 0)
        if sz == 0: continue
        if sec['noload']:
            total_zero += sz
            items.append({"section": sec['name'], "type": "zeroed", "size": sz,
                          "vma": sec['vma'], "lma": sec['lma']})
        elif sec['lma']:
            total_copy += sz
            items.append({"section": sec['name'], "type": "copied", "size": sz,
                          "vma": sec['vma'], "lma": sec['lma']})
    return {"items": items, "total_copy": total_copy, "total_zero": total_zero}


# ─────────────────────────────────────────────────────────────────────────────
# HTML FRONTEND
# ─────────────────────────────────────────────────────────────────────────────

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Linker MemMap</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;700&family=Syne:wght@400;600;700;800&display=swap');
:root{
  --bg:#080b10;--surf:#0d1117;--s2:#161b22;--s3:#1c2330;
  --bdr:#21262d;--txt:#c9d1d9;--dim:#6e7681;
  --acc:#58a6ff;--grn:#3fb950;--ora:#d29922;--red:#f85149;--pur:#bc8cff;
  --mono:'JetBrains Mono',monospace;--ui:'Syne',sans-serif;
}
*{box-sizing:border-box;margin:0;padding:0}
html,body{height:100%}
body{background:var(--bg);color:var(--txt);font-family:var(--mono);font-size:13px;display:flex;flex-direction:column}

/* ── Header ── */
header{background:var(--surf);border-bottom:1px solid var(--bdr);padding:12px 20px;
  display:flex;align-items:center;gap:12px;flex-wrap:wrap;flex-shrink:0;z-index:100;
  position:sticky;top:0}
header h1{font-family:var(--ui);font-size:16px;font-weight:800;color:#fff;letter-spacing:-.5px;white-space:nowrap}
header h1 em{color:var(--acc);font-style:normal}
.chip{background:var(--s2);border:1px solid var(--bdr);border-radius:4px;padding:2px 8px;font-size:11px;color:var(--dim);white-space:nowrap}
.chip.grn{background:#0d2318;border-color:#1a5c2a;color:var(--grn)}
.chip.blu{background:#0d1e33;border-color:#1a3a6a;color:var(--acc)}
.chip.red{background:#200d0d;border-color:#5a1a1a;color:var(--red)}
.hbtn{background:var(--s2);border:1px solid var(--bdr);color:var(--txt);padding:4px 10px;
  border-radius:5px;cursor:pointer;font:11px var(--mono);transition:.15s;white-space:nowrap}
.hbtn:hover{border-color:var(--acc);color:var(--acc)}
.hbtn.act{border-color:var(--acc);color:var(--acc);background:#0c1929}
.spacer{flex:1}

/* ── Layout ── */
.layout{display:flex;flex:1;overflow:hidden}
.sidebar{width:240px;min-width:200px;background:var(--surf);border-right:1px solid var(--bdr);
  display:flex;flex-direction:column;flex-shrink:0;overflow-y:auto}
.main{flex:1;overflow:auto;padding:20px}

/* ── Sidebar ── */
.sb-section{border-bottom:1px solid var(--bdr);padding:14px}
.sb-title{font-family:var(--ui);font-size:10px;font-weight:700;color:var(--dim);
  text-transform:uppercase;letter-spacing:.1em;margin-bottom:10px}
.drop-area{border:2px dashed var(--bdr);border-radius:8px;padding:16px 10px;text-align:center;
  cursor:pointer;transition:.2s;position:relative;background:var(--bg)}
.drop-area:hover,.drop-area.over{border-color:var(--acc);background:#0c1929}
.drop-area input{position:absolute;inset:0;opacity:0;cursor:pointer;width:100%;height:100%}
.drop-area .dico{font-size:24px;margin-bottom:6px}
.drop-area p{font-size:11px;color:var(--dim);line-height:1.4}
.drop-area.has-file{border-color:var(--grn);background:#0d2318}
.drop-area.has-file p{color:var(--grn)}
.file-name{font-size:10px;color:var(--acc);margin-top:6px;word-break:break-all;text-align:left}
.tool-row{display:flex;flex-direction:column;gap:4px;margin-bottom:8px}
.tool-row label{font-size:10px;color:var(--dim)}
.tool-row input{background:var(--bg);border:1px solid var(--bdr);border-radius:4px;
  padding:5px 8px;color:var(--txt);font:11px var(--mono);width:100%;transition:.15s}
.tool-row input:focus{outline:none;border-color:var(--acc)}
.tool-row input.ok{border-color:var(--grn)}
.tool-row input.err{border-color:var(--red)}
.run-btn{width:100%;padding:8px;background:var(--acc);color:#000;border:none;border-radius:6px;
  font:600 12px var(--ui);cursor:pointer;transition:.15s;margin-top:4px}
.run-btn:hover{background:#79baff}
.run-btn:disabled{background:var(--s3);color:var(--dim);cursor:default}

/* ── Tabs ── */
.tabs{display:flex;gap:0;border-bottom:1px solid var(--bdr);margin-bottom:18px;flex-wrap:wrap}
.tab{padding:8px 16px;cursor:pointer;font-size:12px;color:var(--dim);border-bottom:2px solid transparent;
  transition:.15s;white-space:nowrap}
.tab:hover{color:var(--txt)}
.tab.act{color:var(--acc);border-bottom-color:var(--acc)}
.pane{display:none}
.pane.act{display:block}

/* ── Memory map SVG ── */
#mc{background:var(--surf);border:1px solid var(--bdr);border-radius:10px;
  padding:18px;overflow-x:auto;margin-bottom:16px}
#leg{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px}
.li{display:flex;align-items:center;gap:5px;font-size:11px;color:var(--dim)}
.ld{width:10px;height:10px;border-radius:2px;flex-shrink:0}

/* ── Tables ── */
.card-wrap{background:var(--surf);border:1px solid var(--bdr);border-radius:8px;overflow:hidden;margin-bottom:16px}
.tbl-hdr{background:var(--s2);padding:10px 14px;font-family:var(--ui);font-size:12px;
  font-weight:600;color:#fff;display:flex;align-items:center;gap:8px}
.tbl-hdr .sub{font-size:11px;color:var(--dim);font-weight:400;font-family:var(--mono)}
table{width:100%;border-collapse:collapse}
th{background:var(--s2);color:var(--dim);font-size:10px;font-weight:500;text-transform:uppercase;
  letter-spacing:.07em;padding:8px 12px;text-align:left;border-bottom:1px solid var(--bdr);
  cursor:pointer;user-select:none;white-space:nowrap}
th:hover{color:var(--txt)}
th.sort-asc::after{content:' ↑'}
th.sort-desc::after{content:' ↓'}
td{padding:7px 12px;border-bottom:1px solid #0a0e14;font-size:12px;vertical-align:middle;
  max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
tr:last-child td{border-bottom:none}
tr:hover td{background:#0a0f18;cursor:pointer}
.hx{color:var(--acc);font-size:11px}
.sz{color:var(--grn)}
.dim{color:var(--dim)}
.type-badge{display:inline-block;padding:1px 6px;border-radius:3px;font-size:10px;border:1px solid}

/* ── Search / filter ── */
.filter-bar{display:flex;gap:8px;margin-bottom:12px;flex-wrap:wrap;align-items:center}
.search{background:var(--surf);border:1px solid var(--bdr);border-radius:5px;
  padding:6px 10px;color:var(--txt);font:12px var(--mono);flex:1;min-width:180px}
.search:focus{outline:none;border-color:var(--acc)}
select.fsel{background:var(--surf);border:1px solid var(--bdr);border-radius:5px;
  padding:6px 8px;color:var(--txt);font:12px var(--mono);cursor:pointer}
select.fsel:focus{outline:none;border-color:var(--acc)}
.count-badge{font-size:11px;color:var(--dim)}

/* ── Warning cards ── */
.warn-list{display:flex;flex-direction:column;gap:8px}
.wcard{background:var(--surf);border:1px solid var(--bdr);border-radius:8px;
  padding:14px 16px;display:flex;gap:12px;align-items:flex-start}
.wcard.error{border-color:#5a1a1a;background:#150808}
.wcard.warn {border-color:#5a3d1a;background:#100c05}
.wcard.info {border-color:#1a2a3a;background:#08101a}
.wicon{font-size:20px;flex-shrink:0;margin-top:1px}
.wtitle{font-weight:500;color:#fff;font-size:13px;margin-bottom:4px}
.wcat{font-size:10px;color:var(--dim);margin-bottom:6px;text-transform:uppercase;letter-spacing:.07em}
.wdetail{font-size:11px;color:#8b949e;line-height:1.55}

/* ── Startup cost ── */
.startup-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:16px}
.stat-card{background:var(--surf);border:1px solid var(--bdr);border-radius:8px;padding:16px}
.stat-num{font-family:var(--ui);font-size:28px;font-weight:800;color:var(--acc);margin-bottom:4px}
.stat-lbl{font-size:11px;color:var(--dim)}
.startup-row{display:flex;align-items:center;gap:10px;padding:6px 0;border-bottom:1px solid var(--bdr);font-size:12px}
.startup-row:last-child{border:none}
.startup-type{padding:2px 7px;border-radius:3px;font-size:10px;font-weight:500;width:60px;text-align:center}
.copied{background:#0d1e33;color:var(--acc);border:1px solid #1a3a6a}
.zeroed{background:#0d2318;color:var(--grn);border:1px solid #1a5c2a}

/* ── Addr2line panel ── */
.a2l-input{display:flex;gap:8px;margin-bottom:12px}
.a2l-input input{background:var(--surf);border:1px solid var(--bdr);border-radius:5px;
  padding:6px 10px;color:var(--txt);font:12px var(--mono);flex:1}
.a2l-input input:focus{outline:none;border-color:var(--acc)}
.a2l-result{background:var(--surf);border:1px solid var(--bdr);border-radius:8px;padding:14px;
  font-size:12px;color:var(--txt);min-height:60px;white-space:pre-wrap;font-family:var(--mono)}

/* ── Fill bar ── */
.fill-bg{background:var(--s3);border-radius:3px;height:6px;width:80px;display:inline-block;vertical-align:middle}
.fill-bar{height:6px;border-radius:3px}

/* ── Tooltip ── */
#tip{position:fixed;background:#161b22;border:1px solid var(--bdr);border-radius:9px;
  padding:12px 15px;font-size:12px;pointer-events:none;opacity:0;transition:opacity .12s;
  z-index:9999;max-width:300px;box-shadow:0 12px 40px #00000090}
#tip.on{opacity:1}
.tn{font-weight:600;color:#fff;margin-bottom:7px;font-size:13px;font-family:var(--ui)}
.tr{display:flex;justify-content:space-between;gap:16px;color:var(--dim);margin-bottom:3px}
.tv{color:var(--acc)}
.td2{margin-top:8px;color:#8b949e;line-height:1.55;border-top:1px solid var(--bdr);
  padding-top:8px;font-size:11px}
.empty{text-align:center;padding:48px;color:var(--dim)}
.empty .eico{font-size:36px;margin-bottom:12px}
.empty h3{font-family:var(--ui);font-size:15px;color:#fff;margin-bottom:8px}
.empty p{font-size:12px;line-height:1.6}
footer{text-align:center;padding:20px;color:var(--dim);font-size:11px;flex-shrink:0;
  border-top:1px solid var(--bdr)}
</style>
</head>
<body>

<header>
  <h1>Linker <em>MemMap</em></h1>
  <span class="chip">ELF Analyser</span>
  <span class="chip blu" id="fchip" style="display:none">📄 <span id="fname"></span></span>
  <span class="chip blu" id="echip" style="display:none">⚙️ <span id="ename"></span></span>
  <span class="chip grn" id="entry-chip" style="display:none">⚡ <span id="esym"></span></span>
  <span class="chip grn" id="sym-chip" style="display:none"><span id="symcount"></span> symbols</span>
  <div class="spacer"></div>
  <button class="hbtn" onclick="document.getElementById('sidebar').style.display=
    document.getElementById('sidebar').style.display==='none'?'flex':'none'">☰ Sidebar</button>
</header>

<div class="layout">
  <!-- ── Sidebar ── -->
  <div class="sidebar" id="sidebar">
    <!-- Linker file -->
    <div class="sb-section">
      <div class="sb-title">Linker Script (.ld)</div>
      <div class="drop-area" id="ld-drop">
        <input type="file" accept=".ld,.lds,.x" id="ld-fi">
        <div class="dico">📋</div>
        <p>Drop .ld file here</p>
      </div>
      <div class="file-name" id="ld-name" style="display:none"></div>
    </div>

    <!-- ELF file -->
    <div class="sb-section">
      <div class="sb-title">ELF File (optional)</div>
      <div class="drop-area" id="elf-drop">
        <input type="file" id="elf-fi">
        <div class="dico">🔧</div>
        <p>Drop .elf / .axf file<br>for symbol analysis</p>
      </div>
      <div class="file-name" id="elf-name" style="display:none"></div>
    </div>

    <!-- Toolchain -->
    <div class="sb-section">
      <div class="sb-title">Toolchain Paths</div>
      <div class="tool-row">
        <label>nm</label>
        <input id="t-nm" placeholder="arm-none-eabi-nm" value="arm-none-eabi-nm">
      </div>
      <div class="tool-row">
        <label>readelf</label>
        <input id="t-re" placeholder="arm-none-eabi-readelf" value="arm-none-eabi-readelf">
      </div>
      <div class="tool-row">
        <label>size</label>
        <input id="t-sz" placeholder="arm-none-eabi-size" value="arm-none-eabi-size">
      </div>
      <div class="tool-row">
        <label>addr2line</label>
        <input id="t-a2l" placeholder="arm-none-eabi-addr2line" value="arm-none-eabi-addr2line">
      </div>
      <div class="tool-row">
        <label>Full toolchain prefix or path (optional)</label>
        <input id="t-prefix" placeholder="/opt/arm/bin/arm-none-eabi-">
      </div>
      <button class="run-btn" id="analyse-btn" onclick="runAnalysis()" disabled>
        ▶ Analyse ELF
      </button>
      <div style="font-size:10px;color:var(--dim);margin-top:8px;line-height:1.5" id="tool-status"></div>
    </div>
  </div>

  <!-- ── Main content ── -->
  <div class="main" id="main-content">
    <div class="empty" id="welcome">
      <div class="eico">🗂️</div>
      <h3>Drop a linker script to start</h3>
      <p>Load a <strong>.ld</strong> file from the sidebar to visualise your memory map.<br>
         Optionally load an <strong>.elf</strong> file and configure toolchain paths<br>
         for full symbol-level analysis.</p>
    </div>

    <div id="app-content" style="display:none">
      <div class="tabs">
        <div class="tab act" onclick="tab('map')">🗺 Memory Map</div>
        <div class="tab" onclick="tab('sym')" id="tab-sym">🔍 Symbols</div>
        <div class="tab" onclick="tab('sections')" id="tab-sec">📦 Sections</div>
        <div class="tab" onclick="tab('warn')" id="tab-warn">⚠ Warnings <span id="warn-count"></span></div>
        <div class="tab" onclick="tab('startup')" id="tab-su">🚀 Startup Cost</div>
        <div class="tab" onclick="tab('a2l')" id="tab-a2l">📍 Addr→Line</div>
      </div>

      <!-- MAP -->
      <div class="pane act" id="pane-map">
        <div id="mc"><svg id="map-svg"></svg></div>
        <div id="leg"></div>
        <div class="card-wrap">
          <div class="tbl-hdr">Region Summary</div>
          <table><thead><tr>
            <th>Region</th><th>Start</th><th>End</th><th>Size</th>
            <th>Type</th><th>Used</th><th>Free</th><th>Fill</th>
          </tr></thead><tbody id="rtb"></tbody></table>
        </div>
      </div>

      <!-- SYMBOLS -->
      <div class="pane" id="pane-sym">
        <div class="empty" id="sym-empty">
          <div class="eico">⚙️</div>
          <h3>Load an ELF file to explore symbols</h3>
          <p>Drop a .elf file in the sidebar and click <strong>Analyse ELF</strong><br>
             to see all functions and variables with addresses, sizes, and source locations.</p>
        </div>
        <div id="sym-content" style="display:none">
          <div class="filter-bar">
            <input class="search" id="sym-search" placeholder="Search symbols..." oninput="filterSyms()">
            <select class="fsel" id="sym-type" onchange="filterSyms()">
              <option value="">All types</option>
              <option value="function">Functions</option>
              <option value="variable">Variables</option>
              <option value="constant">Constants</option>
              <option value="weak">Weak</option>
              <option value="undefined">Undefined</option>
            </select>
            <select class="fsel" id="sym-sec" onchange="filterSyms()">
              <option value="">All sections</option>
            </select>
            <select class="fsel" id="sym-glob" onchange="filterSyms()">
              <option value="">Global + Local</option>
              <option value="1">Global only</option>
              <option value="0">Local only</option>
            </select>
            <span class="count-badge" id="sym-count-badge"></span>
          </div>
          <div class="card-wrap">
            <table id="sym-table">
              <thead><tr>
                <th onclick="sortSym('name')">Symbol</th>
                <th onclick="sortSym('addr')">Address</th>
                <th onclick="sortSym('size')">Size</th>
                <th onclick="sortSym('type')">Type</th>
                <th onclick="sortSym('section')">Section</th>
                <th>Source</th>
              </tr></thead>
              <tbody id="sym-tbody"></tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- SECTIONS -->
      <div class="pane" id="pane-sections">
        <div id="sec-cards-grid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:10px"></div>
      </div>

      <!-- WARNINGS -->
      <div class="pane" id="pane-warn">
        <div class="warn-list" id="warn-list">
          <div class="empty"><div class="eico">✅</div>
            <h3>No warnings yet</h3><p>Load an ELF file to run analysis</p></div>
        </div>
      </div>

      <!-- STARTUP -->
      <div class="pane" id="pane-startup">
        <div class="startup-grid" id="startup-stats"></div>
        <div class="card-wrap" id="startup-card">
          <div class="tbl-hdr">Copy table — what startup code must do before main()</div>
          <div style="padding:14px" id="startup-rows"></div>
        </div>
      </div>

      <!-- ADDR2LINE -->
      <div class="pane" id="pane-a2l">
        <p style="color:var(--dim);font-size:12px;margin-bottom:12px">
          Enter a hex address to find the corresponding source file and line number.
          Requires addr2line tool and ELF file.
        </p>
        <div class="a2l-input">
          <input id="a2l-addr" placeholder="0x00401234" onkeydown="if(event.key==='Enter')doA2L()">
          <button class="hbtn" onclick="doA2L()">Look up</button>
        </div>
        <div class="a2l-result" id="a2l-result">Result will appear here</div>
        <div style="margin-top:16px;font-size:11px;color:var(--dim)">
          💡 Tip: Click any symbol row to auto-fill its address here.
        </div>
      </div>
    </div>
  </div>
</div>

<div id="tip"></div>
<footer>Linker MemMap Viewer · Drop files anywhere to reload</footer>

<script>
const $=id=>document.getElementById(id);
const NS='http://www.w3.org/2000/svg';
let STATE={ld:null, elf:null, syms:[], elfSecs:{}, warns:[], startup:null,
           symSort:'size', symDir:-1, filteredSyms:[]};
let ldText='', elfPath='';

// ── File drops ────────────────────────────────────────────────────────────────
function setupDrop(dropId, inputId, cb){
  const drop=$( dropId), inp=$(inputId);
  drop.addEventListener('dragover',  e=>{e.preventDefault();drop.classList.add('over')});
  drop.addEventListener('dragleave', ()=>drop.classList.remove('over'));
  drop.addEventListener('drop', e=>{e.preventDefault();drop.classList.remove('over');cb(e.dataTransfer.files[0])});
  inp.addEventListener('change', e=>cb(e.target.files[0]));
}
setupDrop('ld-drop','ld-fi', f=>{
  if(!f)return;
  const r=new FileReader(); r.onload=e=>{ldText=e.target.result; uploadLD(f.name,ldText)};
  r.readAsText(f);
});
setupDrop('elf-drop','elf-fi', f=>{
  if(!f)return;
  elfPath=f.name;  // we'll send the full path from toolchain side
  // We can't read binary in browser directly to run toolchain — send path hint
  $('elf-name').textContent=f.name; $('elf-name').style.display='';
  $('elf-drop').classList.add('has-file');
  $('elf-drop').querySelector('p').textContent=f.name;
  $('echip').style.display=''; $('ename').textContent=f.name;
  $('analyse-btn').disabled=false;
  // Store actual File object for path extraction
  STATE.elfFile=f;
});
window.addEventListener('dragover',e=>e.preventDefault());
window.addEventListener('drop',e=>{
  e.preventDefault();
  const f=e.dataTransfer.files[0];
  if(!f)return;
  const low=f.name.toLowerCase();
  if(low.endsWith('.ld')||low.endsWith('.lds')||low.endsWith('.x')){
    const r=new FileReader(); r.onload=ev=>{ldText=ev.target.result; uploadLD(f.name,ldText)};
    r.readAsText(f);
  }
});

async function uploadLD(name, text){
  const fd=new FormData(); fd.append('content',text); fd.append('filename',name);
  const res=await fetch('/parse_ld',{method:'POST',body:fd});
  const d=await res.json();
  if(d.error){alert(d.error);return}
  STATE.ld=d;
  $('fchip').style.display=''; $('fname').textContent=name;
  $('ld-name').textContent=name; $('ld-name').style.display='';
  $('ld-drop').classList.add('has-file');
  $('ld-drop').querySelector('p').textContent=name;
  if(d.entry){$('entry-chip').style.display='';$('esym').textContent=d.entry}
  $('welcome').style.display='none';
  $('app-content').style.display='';
  renderMap(d);
  renderSections(d);
  renderStartup(d,{},{});
  renderWarnings([]);
}

async function runAnalysis(){
  if(!STATE.elfFile){alert('Please drop an ELF file first');return}
  const btn=$('analyse-btn');
  btn.disabled=true; btn.textContent='⏳ Analysing...';
  $('tool-status').textContent='Running nm, readelf, size...';

  const prefix=$('t-prefix').value.trim();
  const tools={
    nm:   prefix ? prefix+'nm'       : $('t-nm').value.trim(),
    re:   prefix ? prefix+'readelf'  : $('t-re').value.trim(),
    size: prefix ? prefix+'size'     : $('t-sz').value.trim(),
    a2l:  prefix ? prefix+'addr2line': $('t-a2l').value.trim(),
  };

  // We need the real path — ask user to provide full path to ELF
  // since browser File API hides the real path
  const elfPathInput=$('elf-path-input');
  let realElfPath = elfPathInput ? elfPathInput.value.trim() : '';
  if(!realElfPath){
    realElfPath=prompt(
      'Enter the FULL path to your ELF file:\n(Browser cannot access file paths directly)',
      'C:\\path\\to\\your\\project.elf'
    );
  }
  if(!realElfPath){btn.disabled=false;btn.textContent='▶ Analyse ELF';return}

  const fd=new FormData();
  fd.append('elf_path', realElfPath);
  fd.append('tools', JSON.stringify(tools));
  fd.append('ld_data', JSON.stringify(STATE.ld));

  const res=await fetch('/analyse_elf',{method:'POST',body:fd});
  const d=await res.json();
  btn.disabled=false; btn.textContent='▶ Analyse ELF';

  if(d.error){$('tool-status').textContent='❌ '+d.error;return}

  $('tool-status').textContent=`✅ ${d.symbols.length} symbols loaded`;
  STATE.syms=d.symbols; STATE.elfSecs=d.elf_sections;
  STATE.warns=d.warnings; STATE.startup=d.startup;

  $('sym-chip').style.display=''; $('symcount').textContent=d.symbols.length;

  // Update map with real sizes
  if(STATE.ld) renderMap(STATE.ld, d.elf_sections);
  renderSymbols(d.symbols, d.elf_sections);
  renderWarnings(d.warnings);
  renderStartup(STATE.ld, d.elf_sections, d.startup);

  // Populate section filter
  const secSel=$('sym-sec'); secSel.innerHTML='<option value="">All sections</option>';
  const secNames=[...new Set(d.symbols.map(s=>s.section).filter(Boolean))].sort();
  secNames.forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;secSel.appendChild(o)});
}

// ── Tab switching ─────────────────────────────────────────────────────────────
function tab(name){
  document.querySelectorAll('.tab').forEach(t=>t.classList.remove('act'));
  document.querySelectorAll('.pane').forEach(p=>p.classList.remove('act'));
  event.target.classList.add('act');
  $('pane-'+name).classList.add('act');
}

// ── Helpers ───────────────────────────────────────────────────────────────────
const hx=n=>'0x'+n.toString(16).toUpperCase().padStart(8,'0');
function fz(n){
  if(n>=1048576)return(n/1048576).toFixed(2)+' MB';
  if(n>=1024)return(n/1024).toFixed(1)+' KB';
  return n+' B';
}
function mkEl(p,tag,attrs){
  const e=document.createElementNS(NS,tag);
  Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,String(v)));
  p.appendChild(e);return e;
}
function svgTxt(p,text,attrs,pe){
  const e=mkEl(p,'text',{...attrs,'font-family':'JetBrains Mono,monospace','pointer-events':pe||'all'});
  e.textContent=text;return e;
}

// ── SVG Memory Map ────────────────────────────────────────────────────────────
function renderMap(data, elfSecs={}){
  const svg=$('map-svg'); svg.innerHTML='';
  const regs=data.regions.filter(r=>r.length>0);
  if(!regs.length){svg.innerHTML='<text fill="#555" x="20" y="30" font-size="13">No MEMORY block found</text>';return}

  const AW=95,BW=200,LW=220,PAD_T=44,PAD_B=36,MIN_H=30,GAP=4;
  const totalLog=regs.reduce((s,r)=>s+Math.log2(Math.max(r.length,256)),0);
  const CH=Math.max(500,regs.length*100);
  const rh=r=>Math.max(MIN_H,(Math.log2(Math.max(r.length,256))/totalLog)*CH);
  const totalH=regs.reduce((s,r)=>s+rh(r)+GAP,0)+PAD_T+PAD_B;
  svg.setAttribute('width',AW+BW+LW+20);
  svg.setAttribute('height',totalH);
  svg.setAttribute('viewBox',`0 0 ${AW+BW+LW+20} ${totalH}`);

  svgTxt(svg,'ADDRESS',{x:AW/2,y:28,fill:'#6e7681','font-size':9,'text-anchor':'middle','letter-spacing':'0.1em'});
  svgTxt(svg,'REGION / SECTIONS',{x:AW+BW/2,y:28,fill:'#6e7681','font-size':9,'text-anchor':'middle','letter-spacing':'0.1em'});

  let y=PAD_T;
  const RTABLE=[];
  for(const reg of regs){
    const h=rh(reg);
    const usedBytes=reg.sections.reduce((s,sec)=>{
      const es=elfSecs[sec.name];
      return s+(es?es.size:0);
    },0);
    const usedPct=reg.length>0?Math.min(1,usedBytes/reg.length):0;
    const freeBytes=Math.max(0,reg.length-usedBytes);
    RTABLE.push({...reg,usedBytes,usedPct,freeBytes});

    const rb=mkEl(svg,'rect',{x:AW,y,width:BW,height:h,fill:reg.color,rx:4,
      stroke:'#2a3548','stroke-width':1,cursor:'pointer'});
    hover(rb,{name:reg.name,rows:[
      ['Start',hx(reg.origin)],['End',hx(reg.end)],['Size',fz(reg.length)],
      ['Type',reg.type],['Used',usedBytes?fz(usedBytes):'unknown'],
      ['Free',freeBytes?fz(freeBytes):'unknown'],
    ],desc:`Memory region "${reg.name}". ${reg.sections.length} section(s).`});

    // Address labels
    svgTxt(svg,hx(reg.origin),{x:AW-6,y:y+12,fill:'#58a6ff','font-size':9,'text-anchor':'end'});
    svgTxt(svg,hx(reg.end),{x:AW-6,y:y+h,fill:'#3a4450','font-size':9,'text-anchor':'end'});
    // Tick marks
    mkEl(svg,'line',{x1:AW-4,y1:y,x2:AW,y2:y,stroke:'#444','stroke-width':1});
    mkEl(svg,'line',{x1:AW-4,y1:y+h,x2:AW,y2:y+h,stroke:'#333','stroke-width':1});

    // Region label
    svgTxt(svg,reg.name,{x:AW+BW+10,y:y+14,fill:'#fff','font-size':12,'font-weight':600,'font-family':'Syne,sans-serif'});
    svgTxt(svg,fz(reg.length),{x:AW+BW+10,y:y+27,fill:'#6e7681','font-size':10});
    if(usedBytes>0){
      const pctStr=(usedPct*100).toFixed(1)+'%';
      const col=usedPct>0.95?'#f85149':usedPct>0.8?'#d29922':'#3fb950';
      svgTxt(svg,pctStr+' used',{x:AW+BW+10,y:y+40,fill:col,'font-size':10});
    }

    // Sections inside bar
    const secs=reg.sections;
    if(secs.length){
      const sh=Math.max(12,(h-4)/secs.length);
      secs.forEach((sec,i)=>{
        const sy=y+2+i*sh, sH=Math.min(sh,(h-4)-i*sh)-1;
        if(sH<3)return;
        const secSize=elfSecs[sec.name]?elfSecs[sec.name].size:0;
        const sr=mkEl(svg,'rect',{x:AW+2,y:sy,width:BW-4,height:sH,
          fill:sec.color,rx:2,opacity:0.84,cursor:'pointer'});
        hover(sr,{name:sec.name,rows:[
          ['Type',sec.type],['VMA',sec.vma||'—'],['LMA',sec.lma||'—'],
          ['NOLOAD',sec.noload?'Yes':'No'],
          ['Size',secSize?fz(secSize):'(load ELF for size)'],
        ],desc:sec.desc});
        if(sH>14) svgTxt(svg,sec.name,{x:AW+7,y:sy+sH/2+4,fill:'#fff',
          'font-size':Math.min(10,sH-3),'pointer-events':'none'});
      });
    }
    y+=h+GAP;
  }

  // Legend
  const leg=$('leg'); leg.innerHTML='';
  const seen=new Set();
  data.sections.forEach(s=>{
    if(seen.has(s.type))return; seen.add(s.type);
    const d=document.createElement('div'); d.className='li';
    d.innerHTML=`<div class="ld" style="background:${s.color}"></div>${s.type}`;
    leg.appendChild(d);
  });

  // Region table
  const rtb=$('rtb'); rtb.innerHTML='';
  RTABLE.forEach(r=>{
    const pct=r.usedPct;
    const col=pct>0.95?'#f85149':pct>0.8?'#d29922':'#3fb950';
    const bar=pct>0?`<div class="fill-bg"><div class="fill-bar" style="width:${Math.round(pct*80)}px;background:${col}"></div></div>`:'—';
    const tr=document.createElement('tr'); tr.innerHTML=`
      <td><span style="display:inline-block;width:9px;height:9px;border-radius:2px;
        background:${r.color};margin-right:7px;vertical-align:middle"></span>${r.name}</td>
      <td class="hx">${hx(r.origin)}</td><td class="hx">${hx(r.end)}</td>
      <td class="sz">${fz(r.length)}</td><td class="dim">${r.type}</td>
      <td>${r.usedBytes?fz(r.usedBytes):'—'}</td>
      <td>${r.freeBytes&&r.usedBytes?fz(r.freeBytes):'—'}</td>
      <td>${bar}</td>`;
    rtb.appendChild(tr);
  });
}

// ── Sections cards ────────────────────────────────────────────────────────────
function renderSections(data){
  const g=$('sec-cards-grid'); g.innerHTML='';
  data.sections.forEach(s=>{
    const d=document.createElement('div');
    d.style.cssText='background:var(--surf);border:1px solid var(--bdr);border-radius:8px;padding:13px 15px;display:flex;gap:10px';
    d.innerHTML=`
      <div style="width:10px;height:10px;border-radius:2px;background:${s.color};margin-top:3px;flex-shrink:0"></div>
      <div>
        <div style="font-size:12px;font-weight:500;color:#fff;margin-bottom:3px">${s.name}
          ${s.noload?'<span style="font-size:9px;padding:1px 5px;border-radius:3px;background:#200d0d;color:#f85149;border:1px solid #5a1a1a;margin-left:4px">NOLOAD</span>':''}
          ${s.vma?`<span style="font-size:9px;padding:1px 5px;border-radius:3px;background:#0d1a2a;color:#58a6ff;border:1px solid #1a3a6a;margin-left:4px">→ ${s.vma}</span>`:''}
          ${s.lma?`<span style="font-size:9px;padding:1px 5px;border-radius:3px;background:var(--s2);color:var(--dim);border:1px solid var(--bdr);margin-left:4px">LMA:${s.lma}</span>`:''}
          ${s.dma_safe?'<span style="font-size:9px;padding:1px 5px;border-radius:3px;background:#0d2010;color:#3fb950;border:1px solid #1a5c2a;margin-left:4px">DMA-safe</span>':''}
          ${s.cacheable?'<span style="font-size:9px;padding:1px 5px;border-radius:3px;background:#2a1a0d;color:#d29922;border:1px solid #5a3d1a;margin-left:4px">cached</span>':''}
        </div>
        <div style="font-size:10px;color:var(--dim);margin-bottom:5px">${s.type}</div>
        <div style="font-size:11px;color:#8b949e;line-height:1.55">${s.desc}</div>
      </div>`;
    g.appendChild(d);
  });
}

// ── Symbols table ─────────────────────────────────────────────────────────────
const TYPE_COL={'function':'#3b82f6','variable':'#f97316','constant':'#10b981',
  'weak':'#6366f1','undefined':'#6e7681','absolute':'#f59e0b','other':'#374151'};

function renderSymbols(syms, elfSecs){
  $('sym-empty').style.display='none';
  $('sym-content').style.display='';
  STATE.syms=syms; STATE.filteredSyms=[...syms];
  filterSyms();
}

function filterSyms(){
  const q=($('sym-search').value||'').toLowerCase();
  const t=$('sym-type').value;
  const sec=$('sym-sec').value;
  const glob=$('sym-glob').value;
  STATE.filteredSyms=STATE.syms.filter(s=>{
    if(q && !s.name.toLowerCase().includes(q)) return false;
    if(t && s.type!==t) return false;
    if(sec && s.section!==sec) return false;
    if(glob==='1' && !s.global) return false;
    if(glob==='0' && s.global) return false;
    return true;
  });
  sortAndRenderSyms();
}

function sortSym(col){
  if(STATE.symSort===col) STATE.symDir*=-1;
  else{STATE.symSort=col; STATE.symDir=-1}
  document.querySelectorAll('#sym-table th').forEach(th=>{
    th.classList.remove('sort-asc','sort-desc')});
  const th=[...document.querySelectorAll('#sym-table th')];
  const cols=['name','addr','size','type','section'];
  const idx=cols.indexOf(col);
  if(idx>=0) th[idx].classList.add(STATE.symDir>0?'sort-asc':'sort-desc');
  sortAndRenderSyms();
}

function sortAndRenderSyms(){
  const {symSort:col, symDir:dir}=STATE;
  const sorted=[...STATE.filteredSyms].sort((a,b)=>{
    let va=a[col]??'',vb=b[col]??'';
    if(typeof va==='number') return (va-vb)*dir;
    return va.localeCompare(vb)*dir;
  });

  const tbody=$('sym-tbody'); tbody.innerHTML='';
  $('sym-count-badge').textContent=`${sorted.length} of ${STATE.syms.length} symbols`;

  sorted.slice(0,2000).forEach(s=>{
    const col2=TYPE_COL[s.type]||TYPE_COL.other;
    const tr=document.createElement('tr');
    tr.innerHTML=`
      <td style="font-size:11px;color:${s.global?'#fff':'#8b949e'};max-width:280px" title="${s.name}">${s.name}</td>
      <td class="hx">${hx(s.addr)}</td>
      <td class="sz">${s.size?fz(s.size):'—'}</td>
      <td><span class="type-badge" style="color:${col2};border-color:${col2}33;background:${col2}11">${s.type}</span></td>
      <td class="dim" title="${s.section||''}">${s.section||'—'}</td>
      <td class="dim" style="font-size:10px" title="${s.source||''}">${s.source?s.source.split('/').pop():'—'}</td>`;
    tr.addEventListener('click',()=>{
      $('a2l-addr').value=hx(s.addr);
      tab('a2l');
      // fake click on a2l tab
      document.querySelectorAll('.tab').forEach(t=>t.classList.remove('act'));
      document.querySelectorAll('.pane').forEach(p=>p.classList.remove('act'));
      document.querySelector('[onclick="tab(\'a2l\')"]').classList.add('act');
      $('pane-a2l').classList.add('act');
      doA2L();
    });
    tbody.appendChild(tr);
  });
  if(sorted.length>2000){
    const tr=document.createElement('tr');
    tr.innerHTML=`<td colspan="6" style="text-align:center;color:var(--dim);padding:12px">
      ${sorted.length-2000} more symbols — narrow your search filter</td>`;
    tbody.appendChild(tr);
  }
}

// ── Warnings ──────────────────────────────────────────────────────────────────
function renderWarnings(warns){
  const ICONS={error:'🔴',warn:'🟡',info:'🔵'};
  $('warn-count').textContent=warns.length?`(${warns.length})`:'';
  const wl=$('warn-list'); wl.innerHTML='';
  if(!warns.length){
    wl.innerHTML='<div class="empty"><div class="eico">✅</div><h3>No warnings</h3><p>Load ELF to run analysis</p></div>';
    return;
  }
  warns.forEach(w=>{
    const d=document.createElement('div');
    d.className=`wcard ${w.level}`;
    d.innerHTML=`<div class="wicon">${ICONS[w.level]||'ℹ'}</div>
      <div><div class="wcat">${w.category}</div>
      <div class="wtitle">${w.message}</div>
      <div class="wdetail">${w.detail}</div></div>`;
    wl.appendChild(d);
  });
}

// ── Startup cost ──────────────────────────────────────────────────────────────
function renderStartup(ldData, elfSecs, startup){
  const sg=$('startup-stats'); sg.innerHTML='';
  const sr=$('startup-rows'); sr.innerHTML='';
  if(!startup||!startup.items){
    // Estimate from ld alone
    const copySecs=ldData.sections.filter(s=>s.lma&&!s.noload);
    const zeroSecs=ldData.sections.filter(s=>s.noload);
    sg.innerHTML=`
      <div class="stat-card"><div class="stat-num" style="color:var(--acc)">?</div>
        <div class="stat-lbl">Bytes copied flash→RAM<br>(load ELF for exact size)</div></div>
      <div class="stat-card"><div class="stat-num" style="color:var(--grn)">?</div>
        <div class="stat-lbl">Bytes zeroed (BSS)<br>(load ELF for exact size)</div></div>`;
    return;
  }
  const {total_copy,total_zero,items}=startup;
  sg.innerHTML=`
    <div class="stat-card">
      <div class="stat-num" style="color:var(--acc)">${fz(total_copy)}</div>
      <div class="stat-lbl">Copied flash→RAM at startup<br>Larger = slower boot</div></div>
    <div class="stat-card">
      <div class="stat-num" style="color:var(--grn)">${fz(total_zero)}</div>
      <div class="stat-lbl">Zeroed (BSS) at startup<br>Fast — just memset</div></div>`;
  items.forEach(it=>{
    const d=document.createElement('div'); d.className='startup-row';
    d.innerHTML=`
      <span class="startup-type ${it.type}">${it.type}</span>
      <span style="color:#fff;flex:1">${it.section}</span>
      <span class="sz">${fz(it.size)}</span>
      ${it.vma?`<span class="dim" style="font-size:11px">${it.vma}</span>`:''}
      ${it.lma?`<span class="dim" style="font-size:11px">← ${it.lma}</span>`:''}`;
    sr.appendChild(d);
  });
}

// ── Addr2line ─────────────────────────────────────────────────────────────────
async function doA2L(){
  const addr=$('a2l-addr').value.trim();
  if(!addr){return}
  $('a2l-result').textContent='Looking up...';
  const fd=new FormData();
  fd.append('addr',addr);
  fd.append('tools',JSON.stringify({a2l:$('t-prefix').value?$('t-prefix').value+'addr2line':$('t-a2l').value}));
  // Get elf path from prompt or cached
  let ep=STATE.lastElfPath;
  if(!ep){
    ep=prompt('Full path to ELF file:','');
    if(!ep){$('a2l-result').textContent='ELF path required';return}
    STATE.lastElfPath=ep;
  }
  fd.append('elf_path',ep);
  const res=await fetch('/addr2line',{method:'POST',body:fd});
  const d=await res.json();
  $('a2l-result').textContent=d.result||d.error||'No result';
}

// ── Tooltip ───────────────────────────────────────────────────────────────────
const tip=$('tip');
function hover(el,info){
  el.addEventListener('mouseenter',e=>{
    let h=`<div class="tn">${info.name}</div>`;
    info.rows.forEach(([k,v])=>h+=`<div class="tr"><span>${k}</span><span class="tv">${v}</span></div>`);
    if(info.desc)h+=`<div class="td2">${info.desc}</div>`;
    tip.innerHTML=h; tip.classList.add('on'); pos(e);
  });
  el.addEventListener('mousemove',pos);
  el.addEventListener('mouseleave',()=>tip.classList.remove('on'));
}
function pos(e){
  const x=e.clientX+14,y=e.clientY+10;
  const w=tip.offsetWidth||280,h2=tip.offsetHeight||120;
  tip.style.left=Math.min(x,innerWidth-w-8)+'px';
  tip.style.top=Math.min(y,innerHeight-h2-8)+'px';
}
</script>
</body>
</html>
"""

# ─────────────────────────────────────────────────────────────────────────────
# ROUTES
# ─────────────────────────────────────────────────────────────────────────────

@app.route('/')
def index():
    response.content_type = 'text/html; charset=utf-8'
    return HTML

@app.route('/parse_ld', method='POST')
def parse_ld():
    response.content_type = 'application/json'
    try:
        content = request.forms.get('content', '')
        if not content.strip():
            return json.dumps({"error": "Empty file"})
        return json.dumps(parse_linker_script(content))
    except Exception as ex:
        return json.dumps({"error": str(ex)})

@app.route('/analyse_elf', method='POST')
def analyse_elf():
    response.content_type = 'application/json'
    try:
        elf_path = request.forms.get('elf_path', '').strip()
        tools    = json.loads(request.forms.get('tools', '{}'))
        ld_data  = json.loads(request.forms.get('ld_data', '{}'))

        if not elf_path or not os.path.isfile(elf_path):
            return json.dumps({"error": f"ELF file not found: {elf_path!r}"})

        # Resolve tool paths — check both bare name (on PATH) and full path
        def resolve(tool_name, default):
            t = tools.get(tool_name, default).strip()
            if shutil.which(t):
                return t
            # Try common install locations
            for prefix in ['/usr/bin/', '/usr/local/bin/', '/opt/arm/bin/']:
                if os.path.isfile(prefix + t.split('/')[-1]):
                    return prefix + t.split('/')[-1]
            return t  # Return as-is, will fail gracefully

        nm_tool  = resolve('nm',   'arm-none-eabi-nm')
        re_tool  = resolve('re',   'arm-none-eabi-readelf')
        sz_tool  = resolve('size', 'arm-none-eabi-size')

        # Run tools
        symbols     = parse_nm(nm_tool, elf_path)
        elf_secs    = parse_readelf_sections(re_tool, elf_path)
        size_data   = parse_size(sz_tool, elf_path)

        # Merge size data into elf_secs
        for name, s in size_data.items():
            if name in elf_secs:
                if elf_secs[name]['size'] == 0:
                    elf_secs[name]['size'] = s['size']
            else:
                elf_secs[name] = {'addr': s['addr'], 'size': s['size'],
                                  'type': 'PROGBITS', 'flags': ''}

        # Assign symbols to sections
        ld_sections = ld_data.get('sections', [])
        orphans = assign_symbols_to_sections(symbols, elf_secs, ld_sections)

        # Update region used_bytes
        for reg in ld_data.get('regions', []):
            reg['used_bytes'] = sum(
                elf_secs.get(s['name'], {}).get('size', 0)
                for s in reg['sections']
            )

        # Generate warnings
        warnings = generate_warnings(ld_data, elf_secs, symbols)

        # Startup cost
        startup = compute_startup_cost(ld_sections, elf_secs)

        return json.dumps({
            "symbols":      symbols,
            "elf_sections": elf_secs,
            "orphans":      orphans,
            "warnings":     warnings,
            "startup":      startup,
            "ld_data":      ld_data,
        })

    except Exception as ex:
        import traceback
        return json.dumps({"error": str(ex), "trace": traceback.format_exc()})

@app.route('/addr2line', method='POST')
def addr2line_route():
    response.content_type = 'application/json'
    try:
        addr     = request.forms.get('addr', '').strip()
        elf_path = request.forms.get('elf_path', '').strip()
        tools    = json.loads(request.forms.get('tools', '{}'))
        a2l_tool = tools.get('a2l', 'arm-none-eabi-addr2line').strip()

        if not addr:
            return json.dumps({"error": "No address provided"})
        if not elf_path or not os.path.isfile(elf_path):
            return json.dumps({"error": f"ELF not found: {elf_path}"})

        # Parse hex or decimal
        try:
            addr_int = int(addr, 0)
        except ValueError:
            return json.dumps({"error": f"Invalid address: {addr}"})

        stdout, stderr, rc = run_tool([
            a2l_tool, '-e', elf_path, '-f', '-C', '-p', hex(addr_int)
        ])
        result = stdout.strip() or stderr.strip() or "No result"
        return json.dumps({"result": result, "addr": hex(addr_int)})

    except Exception as ex:
        return json.dumps({"error": str(ex)})

@app.route('/check_tool', method='POST')
def check_tool():
    response.content_type = 'application/json'
    tool = request.forms.get('tool', '').strip()
    found = bool(shutil.which(tool))
    return json.dumps({"found": found, "which": shutil.which(tool) or ""})

# ─────────────────────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────

def find_free_port(candidates):
    for port in candidates:
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                s.bind(('localhost', port))
                return port
        except OSError:
            print(f"  Port {port} in use, trying next...")
    return None

def _open(port):
    import time; time.sleep(0.9)
    webbrowser.open(f'http://localhost:{port}')

if __name__ == '__main__':
    CANDIDATES = [5000, 5500, 7000, 7777, 8000, 8080, 8888, 9000, 3000]
    if len(sys.argv) > 1:
        try: CANDIDATES = [int(sys.argv[1])] + CANDIDATES
        except ValueError: pass

    PORT = find_free_port(CANDIDATES)
    if PORT is None:
        print("\n[ERROR] No free port found. Try:  python linker_viewer.py 12345\n")
        sys.exit(1)

    print(f"""
  ╔══════════════════════════════════════════════════╗
  ║  Linker MemMap Viewer                            ║
  ║  http://localhost:{PORT:<5}                         ║
  ║                                                  ║
  ║  1. Drop .ld file in sidebar                     ║
  ║  2. Drop .elf file in sidebar (optional)         ║
  ║  3. Set toolchain path prefix if needed          ║
  ║     e.g.  C:\\arm\\bin\\arm-none-eabi-              ║
  ║  4. Click Analyse ELF                            ║
  ║                                                  ║
  ║  Ctrl+C to stop                                  ║
  ╚══════════════════════════════════════════════════╝
""")
    threading.Thread(target=_open, args=(PORT,), daemon=True).start()
    run(app, host='localhost', port=PORT, quiet=True)
